### ISSUE TITLE
IOS BGP neighbor attributes are not parsed as child of neighbor

### ISSUE THREAD

**Issue by mymodemsux2** [tdorssers/confparser#15]
example for IOS config:

```
router bgp 100
 neighbor 100.100.100.100 remote-as 100
 neighbor 100.100.100.100 shutdown
```

just like BFD, i've added 'shutdown' in the yaml
```
- match: router bgp (?P<local_as>\d+)
  name: bgp
  child:
  - match: bgp router-id (?P<router_id>\S+)
  - match: neighbor (\S+) description (?P<description>.*)
    parent: neighbor
  - match: neighbor (\S+) remote-as (?P<remote_as>.*)
    parent: neighbor
  - match: neighbor (\S+) password 7 (?P<password>\S+)
    parent: neighbor
    actionall: decrypt7
  - match: neighbor (\S+) fall-over bfd
    parent: neighbor
    name: bfd
    action: bool
  - match: neighbor (\S+) shutdown
    parent: neighbor
    name: shutdown
    action: bool
```

and the result is that the key 'shutdown' is under d['bgp']['neighbor'], yet it should be under d['bgp']['neighbor']['100.100.100.100']
