### ISSUE TITLE
Option to force list when duplicate key rather than merging

### ISSUE THREAD

**Issue by Wh1terat** [tdorssers/confparser#8]
Example Config:
```
router static
 address-family ipv4 unicast
  192.0.2.1/32 GigabitEthernet0/0/1/1 1.1.1.1 tag 666 description foo1
  192.0.2.1/32 GigabitEthernet0/0/1/2 2.2.2.2 tag 666 220 description foo2
 ```
Dissector:
```yaml
- match: router static
  name: static
  child:
    - match: address-family (\S+)
      child:
        - match: '([^! ]+)(?: (?=[A-Tn])(?P<interface>\S+))?(?: (?=(?:\S*[\.:])+)(?P<nexthop>\S+))?(?: tag (?P<tag>\d+))?(?: (?P<distance>\d+))?(?: description (?P<description>\S+))?'
    - match: vrf (\S+)
      parent: vrf
      child:
        - match: address-family (\S+)
          child:
          - match: '([^! ]+)(?: vrf (?P<vrf>\S+))?(?: (?=[A-Tn])(?P<interface>\S+))?(?: (?=(?:\S*[\.:])+)(?P<nexthop>\S+))?(?: tag (?P<tag>\d+))?(?: (?P<distance>\d+))?(?: description (?P<description>\S+))?'
```

Output:
```json
    "static": {
        "ipv4": {
            "192.0.2.1/32": {
                "interface": [
                    "GigabitEthernet0/0/1/1",
                    "GigabitEthernet0/0/1/2"
                ],
                "nexthop": [
                    "1.1.1.1",
                    "2.2.2.2"
                ],
                "tag": [
                    "13",
                    "13"
                ],
                "description": [
                    "foo1",
                    "foo2"
                ],
                "distance": "220"
            },
```

Expected output:
```json
    "static": {
        "ipv4": {
            "192.0.2.1/32": [
                {
                    "interface": "GigabitEthernet0/0/1/1",
                    "nexthop": "1.1.1.1",
                    "tag": "666",
                    "description": "foo1",
                },
                {
                    "interface": "GigabitEthernet0/0/1/2",
                    "nexthop": "2.2.2.2",
                    "tag": "666",
                    "description": "foo2",
                    "distance": "220",
                },
            ],            
```

**Comment by tdorssers** [comment]
Use the code from 099a8db and use the new keyword like this:
```
- match: router static
  name: static
  child:
    - match: address-family (\S+)
      child:
        - match: '([^! ]+)(?: (?=[A-Tn])(?P<interface>\S+))?(?: (?=(?:\S*[\.:])+)(?P<nexthop>\S+))?(?: tag (?P<tag>\d+))?(?: (?P<distance>\d+))?(?: description (?P<description>\S+))?'
          grouping: implicit
```
It should output a list when needed and if you use 'explicit' it will always make a list.
